### ISSUE TITLE
Monster movement: Bug

### ISSUE THREAD

**Issue by Sebastian-Noren** [ChristofferQuick/AdventureGame#140]
Errorlog 1: Tror denna händer när man rör på sig in mot ett monster som planerar röra sig mot dig. Och inte att man rör sig till en tom ruta där monstret går in samtidigt. Väldigt säker på detta nu efter ett par tester.

Exception in thread "main" java.lang.NullPointerException
As you enter this room you hear distant screams from orcs and humans who is rallying to war.
at controller.combat_logic.Combat.startCombat(Combat.java:26)
You feel your blood pumping as you ready yourself for battle. your attack power increase by +1.
at controller.Program.run(Program.java:85)
at controller.Program.main(Program.java:42)

**Comment by ChristofferQuick** [comment]
Solved
