### ISSUE TITLE
Monster Movement: Bug 2

### ISSUE THREAD

**Issue by Sebastian-Noren** [ChristofferQuick/AdventureGame#141]
Errorlog 2: Gick in i ett monster längst ut i kanten till vänster. 2,1. All combat som sker i vänsterkanten får felmedelandet. (spelaren går in i ett monster eller om de går rakt mot varandra.) Händer inte om monstret går in i spelaren i vänstra ytterkanten (spelaren rör sig i yttre vänsterkant och monstret jagar ikapp honom i samma rum.

You enter a dark room with a blood pool on the floor.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
at controller.monster_logic.MonsterLogic.hasBoss(MonsterLogic.java:111)
at controller.monster_logic.MonsterLogic.monsterMovement(MonsterLogic.java:33)
at controller.Program.run(Program.java:76)
at controller.Program.main(Program.java:42

**Comment by ChristofferQuick** [comment]
Solved
